# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ubuntu/diy-page-cache-Oleg-cmd

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ubuntu/diy-page-cache-Oleg-cmd

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ubuntu/diy-page-cache-Oleg-cmd/CMakeFiles /home/ubuntu/diy-page-cache-Oleg-cmd//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ubuntu/diy-page-cache-Oleg-cmd/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named diy_cache

# Build rule for target.
diy_cache: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 diy_cache
.PHONY : diy_cache

# fast build rule for target.
diy_cache/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/diy_cache.dir/build.make CMakeFiles/diy_cache.dir/build
.PHONY : diy_cache/fast

#=============================================================================
# Target rules for targets named app

# Build rule for target.
app: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 app
.PHONY : app

# fast build rule for target.
app/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/build
.PHONY : app/fast

#=============================================================================
# Target rules for targets named optimal

# Build rule for target.
optimal: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 optimal
.PHONY : optimal

# fast build rule for target.
optimal/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/optimal.dir/build.make CMakeFiles/optimal.dir/build
.PHONY : optimal/fast

#=============================================================================
# Target rules for targets named search_benchmark

# Build rule for target.
search_benchmark: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 search_benchmark
.PHONY : search_benchmark

# fast build rule for target.
search_benchmark/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/search_benchmark.dir/build.make CMakeFiles/search_benchmark.dir/build
.PHONY : search_benchmark/fast

#=============================================================================
# Target rules for targets named linreg_benchmark

# Build rule for target.
linreg_benchmark: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 linreg_benchmark
.PHONY : linreg_benchmark

# fast build rule for target.
linreg_benchmark/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/linreg_benchmark.dir/build.make CMakeFiles/linreg_benchmark.dir/build
.PHONY : linreg_benchmark/fast

#=============================================================================
# Target rules for targets named pure_search_benchmark

# Build rule for target.
pure_search_benchmark: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 pure_search_benchmark
.PHONY : pure_search_benchmark

# fast build rule for target.
pure_search_benchmark/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pure_search_benchmark.dir/build.make CMakeFiles/pure_search_benchmark.dir/build
.PHONY : pure_search_benchmark/fast

#=============================================================================
# Target rules for targets named pure_linreg_benchmark

# Build rule for target.
pure_linreg_benchmark: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 pure_linreg_benchmark
.PHONY : pure_linreg_benchmark

# fast build rule for target.
pure_linreg_benchmark/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pure_linreg_benchmark.dir/build.make CMakeFiles/pure_linreg_benchmark.dir/build
.PHONY : pure_linreg_benchmark/fast

#=============================================================================
# Target rules for targets named test_storage

# Build rule for target.
test_storage: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_storage
.PHONY : test_storage

# fast build rule for target.
test_storage/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_storage.dir/build.make CMakeFiles/test_storage.dir/build
.PHONY : test_storage/fast

src/app/app.o: src/app/app.cpp.o
.PHONY : src/app/app.o

# target to build an object file
src/app/app.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/app/app.cpp.o
.PHONY : src/app/app.cpp.o

src/app/app.i: src/app/app.cpp.i
.PHONY : src/app/app.i

# target to preprocess a source file
src/app/app.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/app/app.cpp.i
.PHONY : src/app/app.cpp.i

src/app/app.s: src/app/app.cpp.s
.PHONY : src/app/app.s

# target to generate assembly for a file
src/app/app.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/app/app.cpp.s
.PHONY : src/app/app.cpp.s

src/app/optimal.o: src/app/optimal.cpp.o
.PHONY : src/app/optimal.o

# target to build an object file
src/app/optimal.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/optimal.dir/build.make CMakeFiles/optimal.dir/src/app/optimal.cpp.o
.PHONY : src/app/optimal.cpp.o

src/app/optimal.i: src/app/optimal.cpp.i
.PHONY : src/app/optimal.i

# target to preprocess a source file
src/app/optimal.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/optimal.dir/build.make CMakeFiles/optimal.dir/src/app/optimal.cpp.i
.PHONY : src/app/optimal.cpp.i

src/app/optimal.s: src/app/optimal.cpp.s
.PHONY : src/app/optimal.s

# target to generate assembly for a file
src/app/optimal.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/optimal.dir/build.make CMakeFiles/optimal.dir/src/app/optimal.cpp.s
.PHONY : src/app/optimal.cpp.s

src/benchmarks/linreg_benchmark.o: src/benchmarks/linreg_benchmark.cpp.o
.PHONY : src/benchmarks/linreg_benchmark.o

# target to build an object file
src/benchmarks/linreg_benchmark.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/optimal.dir/build.make CMakeFiles/optimal.dir/src/benchmarks/linreg_benchmark.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/linreg_benchmark.dir/build.make CMakeFiles/linreg_benchmark.dir/src/benchmarks/linreg_benchmark.cpp.o
.PHONY : src/benchmarks/linreg_benchmark.cpp.o

src/benchmarks/linreg_benchmark.i: src/benchmarks/linreg_benchmark.cpp.i
.PHONY : src/benchmarks/linreg_benchmark.i

# target to preprocess a source file
src/benchmarks/linreg_benchmark.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/optimal.dir/build.make CMakeFiles/optimal.dir/src/benchmarks/linreg_benchmark.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/linreg_benchmark.dir/build.make CMakeFiles/linreg_benchmark.dir/src/benchmarks/linreg_benchmark.cpp.i
.PHONY : src/benchmarks/linreg_benchmark.cpp.i

src/benchmarks/linreg_benchmark.s: src/benchmarks/linreg_benchmark.cpp.s
.PHONY : src/benchmarks/linreg_benchmark.s

# target to generate assembly for a file
src/benchmarks/linreg_benchmark.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/optimal.dir/build.make CMakeFiles/optimal.dir/src/benchmarks/linreg_benchmark.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/linreg_benchmark.dir/build.make CMakeFiles/linreg_benchmark.dir/src/benchmarks/linreg_benchmark.cpp.s
.PHONY : src/benchmarks/linreg_benchmark.cpp.s

src/benchmarks/linreg_ex.o: src/benchmarks/linreg_ex.cpp.o
.PHONY : src/benchmarks/linreg_ex.o

# target to build an object file
src/benchmarks/linreg_ex.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/linreg_benchmark.dir/build.make CMakeFiles/linreg_benchmark.dir/src/benchmarks/linreg_ex.cpp.o
.PHONY : src/benchmarks/linreg_ex.cpp.o

src/benchmarks/linreg_ex.i: src/benchmarks/linreg_ex.cpp.i
.PHONY : src/benchmarks/linreg_ex.i

# target to preprocess a source file
src/benchmarks/linreg_ex.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/linreg_benchmark.dir/build.make CMakeFiles/linreg_benchmark.dir/src/benchmarks/linreg_ex.cpp.i
.PHONY : src/benchmarks/linreg_ex.cpp.i

src/benchmarks/linreg_ex.s: src/benchmarks/linreg_ex.cpp.s
.PHONY : src/benchmarks/linreg_ex.s

# target to generate assembly for a file
src/benchmarks/linreg_ex.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/linreg_benchmark.dir/build.make CMakeFiles/linreg_benchmark.dir/src/benchmarks/linreg_ex.cpp.s
.PHONY : src/benchmarks/linreg_ex.cpp.s

src/benchmarks/pure_linreg_benchmark.o: src/benchmarks/pure_linreg_benchmark.cpp.o
.PHONY : src/benchmarks/pure_linreg_benchmark.o

# target to build an object file
src/benchmarks/pure_linreg_benchmark.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pure_linreg_benchmark.dir/build.make CMakeFiles/pure_linreg_benchmark.dir/src/benchmarks/pure_linreg_benchmark.cpp.o
.PHONY : src/benchmarks/pure_linreg_benchmark.cpp.o

src/benchmarks/pure_linreg_benchmark.i: src/benchmarks/pure_linreg_benchmark.cpp.i
.PHONY : src/benchmarks/pure_linreg_benchmark.i

# target to preprocess a source file
src/benchmarks/pure_linreg_benchmark.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pure_linreg_benchmark.dir/build.make CMakeFiles/pure_linreg_benchmark.dir/src/benchmarks/pure_linreg_benchmark.cpp.i
.PHONY : src/benchmarks/pure_linreg_benchmark.cpp.i

src/benchmarks/pure_linreg_benchmark.s: src/benchmarks/pure_linreg_benchmark.cpp.s
.PHONY : src/benchmarks/pure_linreg_benchmark.s

# target to generate assembly for a file
src/benchmarks/pure_linreg_benchmark.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pure_linreg_benchmark.dir/build.make CMakeFiles/pure_linreg_benchmark.dir/src/benchmarks/pure_linreg_benchmark.cpp.s
.PHONY : src/benchmarks/pure_linreg_benchmark.cpp.s

src/benchmarks/pure_search_benchmark.o: src/benchmarks/pure_search_benchmark.cpp.o
.PHONY : src/benchmarks/pure_search_benchmark.o

# target to build an object file
src/benchmarks/pure_search_benchmark.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pure_search_benchmark.dir/build.make CMakeFiles/pure_search_benchmark.dir/src/benchmarks/pure_search_benchmark.cpp.o
.PHONY : src/benchmarks/pure_search_benchmark.cpp.o

src/benchmarks/pure_search_benchmark.i: src/benchmarks/pure_search_benchmark.cpp.i
.PHONY : src/benchmarks/pure_search_benchmark.i

# target to preprocess a source file
src/benchmarks/pure_search_benchmark.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pure_search_benchmark.dir/build.make CMakeFiles/pure_search_benchmark.dir/src/benchmarks/pure_search_benchmark.cpp.i
.PHONY : src/benchmarks/pure_search_benchmark.cpp.i

src/benchmarks/pure_search_benchmark.s: src/benchmarks/pure_search_benchmark.cpp.s
.PHONY : src/benchmarks/pure_search_benchmark.s

# target to generate assembly for a file
src/benchmarks/pure_search_benchmark.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pure_search_benchmark.dir/build.make CMakeFiles/pure_search_benchmark.dir/src/benchmarks/pure_search_benchmark.cpp.s
.PHONY : src/benchmarks/pure_search_benchmark.cpp.s

src/benchmarks/search_benchmark.o: src/benchmarks/search_benchmark.cpp.o
.PHONY : src/benchmarks/search_benchmark.o

# target to build an object file
src/benchmarks/search_benchmark.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/optimal.dir/build.make CMakeFiles/optimal.dir/src/benchmarks/search_benchmark.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/search_benchmark.dir/build.make CMakeFiles/search_benchmark.dir/src/benchmarks/search_benchmark.cpp.o
.PHONY : src/benchmarks/search_benchmark.cpp.o

src/benchmarks/search_benchmark.i: src/benchmarks/search_benchmark.cpp.i
.PHONY : src/benchmarks/search_benchmark.i

# target to preprocess a source file
src/benchmarks/search_benchmark.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/optimal.dir/build.make CMakeFiles/optimal.dir/src/benchmarks/search_benchmark.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/search_benchmark.dir/build.make CMakeFiles/search_benchmark.dir/src/benchmarks/search_benchmark.cpp.i
.PHONY : src/benchmarks/search_benchmark.cpp.i

src/benchmarks/search_benchmark.s: src/benchmarks/search_benchmark.cpp.s
.PHONY : src/benchmarks/search_benchmark.s

# target to generate assembly for a file
src/benchmarks/search_benchmark.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/optimal.dir/build.make CMakeFiles/optimal.dir/src/benchmarks/search_benchmark.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/search_benchmark.dir/build.make CMakeFiles/search_benchmark.dir/src/benchmarks/search_benchmark.cpp.s
.PHONY : src/benchmarks/search_benchmark.cpp.s

src/benchmarks/search_ex.o: src/benchmarks/search_ex.cpp.o
.PHONY : src/benchmarks/search_ex.o

# target to build an object file
src/benchmarks/search_ex.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/search_benchmark.dir/build.make CMakeFiles/search_benchmark.dir/src/benchmarks/search_ex.cpp.o
.PHONY : src/benchmarks/search_ex.cpp.o

src/benchmarks/search_ex.i: src/benchmarks/search_ex.cpp.i
.PHONY : src/benchmarks/search_ex.i

# target to preprocess a source file
src/benchmarks/search_ex.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/search_benchmark.dir/build.make CMakeFiles/search_benchmark.dir/src/benchmarks/search_ex.cpp.i
.PHONY : src/benchmarks/search_ex.cpp.i

src/benchmarks/search_ex.s: src/benchmarks/search_ex.cpp.s
.PHONY : src/benchmarks/search_ex.s

# target to generate assembly for a file
src/benchmarks/search_ex.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/search_benchmark.dir/build.make CMakeFiles/search_benchmark.dir/src/benchmarks/search_ex.cpp.s
.PHONY : src/benchmarks/search_ex.cpp.s

src/diy_cache/cache.o: src/diy_cache/cache.cpp.o
.PHONY : src/diy_cache/cache.o

# target to build an object file
src/diy_cache/cache.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/diy_cache.dir/build.make CMakeFiles/diy_cache.dir/src/diy_cache/cache.cpp.o
.PHONY : src/diy_cache/cache.cpp.o

src/diy_cache/cache.i: src/diy_cache/cache.cpp.i
.PHONY : src/diy_cache/cache.i

# target to preprocess a source file
src/diy_cache/cache.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/diy_cache.dir/build.make CMakeFiles/diy_cache.dir/src/diy_cache/cache.cpp.i
.PHONY : src/diy_cache/cache.cpp.i

src/diy_cache/cache.s: src/diy_cache/cache.cpp.s
.PHONY : src/diy_cache/cache.s

# target to generate assembly for a file
src/diy_cache/cache.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/diy_cache.dir/build.make CMakeFiles/diy_cache.dir/src/diy_cache/cache.cpp.s
.PHONY : src/diy_cache/cache.cpp.s

src/diy_cache/lab2_api.o: src/diy_cache/lab2_api.cpp.o
.PHONY : src/diy_cache/lab2_api.o

# target to build an object file
src/diy_cache/lab2_api.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/diy_cache.dir/build.make CMakeFiles/diy_cache.dir/src/diy_cache/lab2_api.cpp.o
.PHONY : src/diy_cache/lab2_api.cpp.o

src/diy_cache/lab2_api.i: src/diy_cache/lab2_api.cpp.i
.PHONY : src/diy_cache/lab2_api.i

# target to preprocess a source file
src/diy_cache/lab2_api.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/diy_cache.dir/build.make CMakeFiles/diy_cache.dir/src/diy_cache/lab2_api.cpp.i
.PHONY : src/diy_cache/lab2_api.cpp.i

src/diy_cache/lab2_api.s: src/diy_cache/lab2_api.cpp.s
.PHONY : src/diy_cache/lab2_api.s

# target to generate assembly for a file
src/diy_cache/lab2_api.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/diy_cache.dir/build.make CMakeFiles/diy_cache.dir/src/diy_cache/lab2_api.cpp.s
.PHONY : src/diy_cache/lab2_api.cpp.s

src/diy_cache/page.o: src/diy_cache/page.cpp.o
.PHONY : src/diy_cache/page.o

# target to build an object file
src/diy_cache/page.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/diy_cache.dir/build.make CMakeFiles/diy_cache.dir/src/diy_cache/page.cpp.o
.PHONY : src/diy_cache/page.cpp.o

src/diy_cache/page.i: src/diy_cache/page.cpp.i
.PHONY : src/diy_cache/page.i

# target to preprocess a source file
src/diy_cache/page.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/diy_cache.dir/build.make CMakeFiles/diy_cache.dir/src/diy_cache/page.cpp.i
.PHONY : src/diy_cache/page.cpp.i

src/diy_cache/page.s: src/diy_cache/page.cpp.s
.PHONY : src/diy_cache/page.s

# target to generate assembly for a file
src/diy_cache/page.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/diy_cache.dir/build.make CMakeFiles/diy_cache.dir/src/diy_cache/page.cpp.s
.PHONY : src/diy_cache/page.cpp.s

src/diy_cache/storage.o: src/diy_cache/storage.cpp.o
.PHONY : src/diy_cache/storage.o

# target to build an object file
src/diy_cache/storage.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/diy_cache.dir/build.make CMakeFiles/diy_cache.dir/src/diy_cache/storage.cpp.o
.PHONY : src/diy_cache/storage.cpp.o

src/diy_cache/storage.i: src/diy_cache/storage.cpp.i
.PHONY : src/diy_cache/storage.i

# target to preprocess a source file
src/diy_cache/storage.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/diy_cache.dir/build.make CMakeFiles/diy_cache.dir/src/diy_cache/storage.cpp.i
.PHONY : src/diy_cache/storage.cpp.i

src/diy_cache/storage.s: src/diy_cache/storage.cpp.s
.PHONY : src/diy_cache/storage.s

# target to generate assembly for a file
src/diy_cache/storage.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/diy_cache.dir/build.make CMakeFiles/diy_cache.dir/src/diy_cache/storage.cpp.s
.PHONY : src/diy_cache/storage.cpp.s

test/test_storage.o: test/test_storage.cpp.o
.PHONY : test/test_storage.o

# target to build an object file
test/test_storage.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_storage.dir/build.make CMakeFiles/test_storage.dir/test/test_storage.cpp.o
.PHONY : test/test_storage.cpp.o

test/test_storage.i: test/test_storage.cpp.i
.PHONY : test/test_storage.i

# target to preprocess a source file
test/test_storage.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_storage.dir/build.make CMakeFiles/test_storage.dir/test/test_storage.cpp.i
.PHONY : test/test_storage.cpp.i

test/test_storage.s: test/test_storage.cpp.s
.PHONY : test/test_storage.s

# target to generate assembly for a file
test/test_storage.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_storage.dir/build.make CMakeFiles/test_storage.dir/test/test_storage.cpp.s
.PHONY : test/test_storage.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... app"
	@echo "... diy_cache"
	@echo "... linreg_benchmark"
	@echo "... optimal"
	@echo "... pure_linreg_benchmark"
	@echo "... pure_search_benchmark"
	@echo "... search_benchmark"
	@echo "... test_storage"
	@echo "... src/app/app.o"
	@echo "... src/app/app.i"
	@echo "... src/app/app.s"
	@echo "... src/app/optimal.o"
	@echo "... src/app/optimal.i"
	@echo "... src/app/optimal.s"
	@echo "... src/benchmarks/linreg_benchmark.o"
	@echo "... src/benchmarks/linreg_benchmark.i"
	@echo "... src/benchmarks/linreg_benchmark.s"
	@echo "... src/benchmarks/linreg_ex.o"
	@echo "... src/benchmarks/linreg_ex.i"
	@echo "... src/benchmarks/linreg_ex.s"
	@echo "... src/benchmarks/pure_linreg_benchmark.o"
	@echo "... src/benchmarks/pure_linreg_benchmark.i"
	@echo "... src/benchmarks/pure_linreg_benchmark.s"
	@echo "... src/benchmarks/pure_search_benchmark.o"
	@echo "... src/benchmarks/pure_search_benchmark.i"
	@echo "... src/benchmarks/pure_search_benchmark.s"
	@echo "... src/benchmarks/search_benchmark.o"
	@echo "... src/benchmarks/search_benchmark.i"
	@echo "... src/benchmarks/search_benchmark.s"
	@echo "... src/benchmarks/search_ex.o"
	@echo "... src/benchmarks/search_ex.i"
	@echo "... src/benchmarks/search_ex.s"
	@echo "... src/diy_cache/cache.o"
	@echo "... src/diy_cache/cache.i"
	@echo "... src/diy_cache/cache.s"
	@echo "... src/diy_cache/lab2_api.o"
	@echo "... src/diy_cache/lab2_api.i"
	@echo "... src/diy_cache/lab2_api.s"
	@echo "... src/diy_cache/page.o"
	@echo "... src/diy_cache/page.i"
	@echo "... src/diy_cache/page.s"
	@echo "... src/diy_cache/storage.o"
	@echo "... src/diy_cache/storage.i"
	@echo "... src/diy_cache/storage.s"
	@echo "... test/test_storage.o"
	@echo "... test/test_storage.i"
	@echo "... test/test_storage.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

