FROM ubuntu:latest

RUN apt update
RUN apt install -y --allow-unauthenticated \
    clang \
    git \
    tree \
    clang-tidy \
    clang-format \
    clangd \
    make \
    ninja \
    libgtest-dev \
    valgrind \
    cmake
